# Generated by Django 3.0.2 on 2020-01-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200106_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupotp',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
    ]
