# Generated by Django 3.0.2 on 2020-01-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_signupotp_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupotp',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
