# Generated by Django 3.0.2 on 2020-01-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_city', '0002_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
